# ===================
# Main Configuration
# ===================

settings:
  # Choose the default language for the plugin
  # Available options: en (English), vi (Vietnamese)
  language: en

  # Enable debug mode to print detailed information to console
  # Useful for troubleshooting issues
  debug: false

  # How often (in ticks) the plugin saves data
  # 20 ticks = 1 second
  # Default: 6000 ticks (5 minutes)
  save-interval: 6000

# ===================
# Spawner Settings
# ===================

spawner:
  # Default entity type when creating new spawners
  default-entity: PIG

  # Experience points configuration
  # Maximum amount of exp points that can be stored in a spawner
  max-stored-exp: 1000

  # Allow players to repair items with mending using stored exp
  allow-exp-mending: true

  # Spawn Control Settings
  # ---------------------
  # Minimum number of mobs to spawn for loot/exp (must be >= 1)
  min-mobs: 1

  # Maximum number of mobs to spawn for loot/exp (must be > min-mobs)
  max-mobs: 4

  # Required player proximity (in blocks) for spawner activation
  range: 16

  # Base spawn delay in ticks (default: 600 ticks = 30 seconds)
  delay: 600

  # Maximum number of entities that can be stacked in one spawner
  max-stack-size: 1000

  # Allow toggling of equipment items drop on spawned mobs
  allow-toggle-equipment-items: true

# ===================
# Breaking Settings
# ===================

spawner-break:
  # Enable/disable spawner breaking functionality
  enabled: true

  # Tools that can break spawners
  required-tools:
#    - WOODEN_PICKAXE # Uncomment to enable
    - STONE_PICKAXE
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
    - NETHERITE_PICKAXE

  # Durability cost when breaking a spawner
  durability-loss-per-spawner: 1

  # Silk Touch Requirements
  silk-touch:
    # Whether Silk Touch is needed to break spawners
    required: true
    # Required Silk Touch enchantment level
    level: 1

  # Stack Drop Settings
  drop-stack:
    # Maximum stack size that will drop as a single item
    # If stack size is smaller, entire stack will drop
    amount: 64

# ===================
# Performance Settings
# ===================

performance:
  # Batch processing size for mob loot/exp drops
  # Lower values = more random but higher resource usage
  # Higher values = more consistent but lower resource usage
  # Recommended range: 1-5
  batch-size: 3

# ===================
# Update Settings
# ===================

update-checker:
  # Enable automatic update checking
  enabled: true

  # Time between update checks (in hours not ticks)
  check-interval: 24

  # Whether to notify server operators about updates when found
  notify-ops: true

  # Whether to notify operators when they join the server
  notify-on-join: true