name: Gradle Build and Publish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.8

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Extract version
      id: extract_version
      run: |
        VERSION=$(grep 'version =' build.gradle | head -n 1 | awk -F "'" '{print $2}')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version: $VERSION"

    - name: Upload plugin JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmartSpawner-${{ env.VERSION }}
        path: build/libs/SmartSpawner-${{ env.VERSION }}.jar
        retention-days: 30
